### PR TITLE
Analyse examples with PHPStan

### LINKED ISSUE #1157: Static analysis error when iterating getFacet result
**Solarium version(s) affected**: 6.3.7
**Solr version**: 7.x.x
**Solr mode**: cloud

**Description**
Iterating a `getFacet` result generates an error with static analysis (PHPStan)

**How to reproduce**
```
$facetResults = $resultset->getFacetSet()->getFacet('facetCounts');

foreach($facetResults as $result) {
    print_r($result);
}
```

**Possible Solution**
`interface FacetResultInterface extends Iterable`

**Additional context**
Argument of an invalid type                                        
         Solarium\Component\Result\Facet\FacetResultInterface supplied for  
         foreach, only iterables are supported.

### PR DESCRIPTION
**Pull request by thomascorthals**
Closes #1157.

### CODE REVIEW

File: src/Core/Client/Client.php [hunk 1]
```diff
@@ -611,15 +615,15 @@ public function setEventDispatcher(EventDispatcherInterface $eventDispatcher): s
      * This requires the availability of the class through autoloading
      * or a manual require.
      *
-     * @param string                 $key
-     * @param string|PluginInterface $plugin
-     * @param array                  $options
+     * @param string                       $key
+     * @param class-string|PluginInterface $plugin
```
Comment (thePanz) [inline src/Core/Client/Client.php]: IIRC we can define and restrict the the class-string too like that:
```suggestion
     * @param class-string<PluginInterface>|PluginInterface $plugin
```

**Review by thePanz — DISMISSED** [review]
