### PR TITLE
Include coding styles fixes

### LINKED ISSUE #558: Include Coding stles fixes
I suggest to include and run php-cs-fixer on the main code of the project, just to comply to some coding standards.

### PR DESCRIPTION
**Pull request by thePanz**
Closes #558

### CODE REVIEW

File: src/Core/Query/Query.php [hunk 1]
```diff
@@ -1,47 +1,9 @@
...
-
-/**
- * @namespace
- */
 
 namespace Solarium\Core\Query;
 
 /**
- * This class is for backwards compatibility, will be removed in 4.x releases in favor of AbstractQuery
+ * This class is for backwards compatibility, will be removed in 4.x releases in favor of AbstractQuery.
```
Comment (mkalkbrenner) [inline src/Core/Query/Query.php]: Should we really remove that class or remove the comment?

File: src/Core/Query/RequestBuilder.php [hunk 2]
```diff
@@ -1,47 +1,9 @@
...
-
-/**
- * @namespace
- */
 
 namespace Solarium\Core\Query;
 
 /**
- * This class is for backwards compatibility, will be removed in 4.x releases in favor of AbstractRequestBuilder
+ * This class is for backwards compatibility, will be removed in 4.x releases in favor of AbstractRequestBuilder.
```
Comment (mkalkbrenner) [inline src/Core/Query/RequestBuilder.php]: Should we really remove that class or remove the comment?

File: src/Core/Query/ResponseParser.php [hunk 3]
```diff
@@ -1,47 +1,9 @@
...
-
-/**
- * @namespace
- */
 
 namespace Solarium\Core\Query;
 
 /**
- * This class is for backwards compatibility, will be removed in 4.x releases in favor of AbstractResponseParser
+ * This class is for backwards compatibility, will be removed in 4.x releases in favor of AbstractResponseParser.
```
Comment (mkalkbrenner) [inline src/Core/Query/ResponseParser.php]: Should we really remove that class or remove the comment?

File: .php_cs.dist [hunk 4]
```diff
@@ -0,0 +1,38 @@
+<?php
```
Comment (mkalkbrenner) [inline .php_cs.dist]: Should this file be excluded in .gitattributes?

File: .styleci.yml [hunk 5]
```diff
@@ -0,0 +1,18 @@
+preset: symfony
```
Comment (mkalkbrenner) [inline .styleci.yml]: Should this file be excluded in .gitattributes?

File: .php_cs.dist [hunk 6]
```diff
@@ -0,0 +1,38 @@
...
+       'ordered_class_elements' => true,
+       'class_attributes_separation' => ['elements' => ['const', 'method', 'property']],
+       'ordered_imports' => true,
+       # 'php_unit_strict' => true,
+       # 'php_unit_test_class_requires_covers' => true,
+       'phpdoc_add_missing_param_annotation' => true,
+       'phpdoc_order' => true,
+       'semicolon_after_instruction' => true,
+       # 'strict_comparison' => true,
+       'strict_param' => true,
```
Comment (localheinz) [inline .php_cs.dist]: I would suggest to keep these rules sorted by key, makes it easier to find if rules have been added or not.

File: .styleci.yml (hunk 5 above)
Comment (localheinz) [reply .styleci.yml]: How about removing the entire file, and instead of using StyleCI, providing an easy means to run coding style fixes as a developer? There's also the problem of having two different configurations now - one for Travis CI, one for StyleCI.

File: src/Client/SolrClient.php [hunk 7]
```diff
@@ -0,0 +1,50 @@
...
+
+namespace Solarium\Client;
+
+use Http\Client\HttpClient;
+use Http\Message\MessageFactory;
+use Psr\Http\Message\RequestInterface;
+use Solarium\Core\Query\ResponseParserInterface;
+use Symfony\Component\EventDispatcher\EventDispatcherInterface;
+
+class SolrClient
```
[the remark this answers is not in the document]
Comment (thePanz) [reply src/Client/SolrClient.php]: Damn, this file should not be here! it was a preliminary implementation of the php-http integration!

File: src/Client/SolrClientBuilder.php [hunk 8]
```diff
@@ -0,0 +1,53 @@
+<?php
+
+namespace Solarium\Client;
+
+use Http\Client\HttpClient;
+use Http\Discovery\HttpClientDiscovery;
+use Http\Discovery\MessageFactoryDiscovery;
+use Http\Message\MessageFactory;
+
+final class SolrClientBuilder
```
[the remark this answers is not in the document]
Comment (thePanz) [reply src/Client/SolrClientBuilder.php]: Damn, this file should not be here! it was a preliminary implementation of the php-http integration!

File: src/Autoloader.php [hunk 9]
```diff
@@ -66,7 +28,7 @@ class Autoloader
      */
     public static function register()
     {
-        spl_autoload_register(array(new self(), 'load'));
+        spl_autoload_register([new self(), 'load']);
```
[the remark this answers is not in the document]
Comment (thePanz) [reply src/Autoloader.php]: Still: the Autoloader.php is a mistery... where is it used??

File: .styleci.yml (hunk 5 above)
Comment (thePanz) [reply .styleci.yml]: There would be a nice solution (like implemented by php-http): using a bridge component that allows style-ci to be defined, and php-cs-fixer to be able to read it.
It is called php-cs-fixer-bridge or something similar.

But still. we could keep the two files, as a CS change is quite improbable after we agreed on a standard. WDYT?

File: .php_cs.dist (hunk 6 above)
Comment (mkalkbrenner) [reply .php_cs.dist]: I second @localheinz

File: src/Autoloader.php (hunk 9 above)
[the remark this answers is not in the document]
Comment (mkalkbrenner) [reply src/Autoloader.php]: We should open a separate issue for further investigation.

File: src/Core/Query/Query.php (hunk 1 above)
Comment (mkalkbrenner) [reply src/Core/Query/Query.php]: We should open a separate issue for further investigation.

File: src/Core/Query/RequestBuilder.php (hunk 2 above)
Comment (mkalkbrenner) [reply src/Core/Query/RequestBuilder.php]: We should open a separate issue for further investigation.

File: src/Core/Query/ResponseParser.php (hunk 3 above)
Comment (mkalkbrenner) [reply src/Core/Query/ResponseParser.php]: We should open a separate issue for further investigation.

File: .styleci.yml (hunk 5 above)
Comment (mkalkbrenner) [reply .styleci.yml]: I think we should start with this new file and open a follow-up issue for further discussion.
I don't want to block 4.0.0-alpha.1

Comment (thePanz) [reply .styleci.yml]: Ok! great

File: .php_cs.dist (hunk 6 above)
Comment (thePanz) [reply .php_cs.dist]: Fixed

File: .php_cs.dist (hunk 4 above)
Comment (thePanz) [reply .php_cs.dist]: Fixed

File: src/Core/Query/ResponseParser.php (hunk 3 above)
Comment (thePanz) [reply src/Core/Query/ResponseParser.php]: Issue opened: #564

File: src/Core/Query/RequestBuilder.php (hunk 2 above)
Comment (thePanz) [reply src/Core/Query/RequestBuilder.php]: Issue opened: #564

File: src/Core/Query/Query.php (hunk 1 above)
Comment (thePanz) [reply src/Core/Query/Query.php]: Issue opened: #564
