### PR TITLE
Fix bug with empty array for multiValued field

### LINKED ISSUE #1023: Since 6.2.5, missing required field id when indexing an empty array
**Solarium version(s) affected**: 6.2.5
**Solr version**: 8.11

**Description**  

Solr complains about missing `id` field but this field is present in every Document. This issue started to occur after upgrading to solarium 6.2.5. This is issue does not occur on 6.2.4:

```
Solr HTTP error: OK (400)                                          
  {                                                                  
    "responseHeader":{                                               
      "status":400,                                                  
      "QTime":1},                                                    
    "error":{                                                        
      "metadata":[                                                   
        "error-class","org.apache.solr.common.SolrException",        
        "root-error-class","org.apache.solr.common.SolrException"],  
      "msg":"[doc=null] missing required field: id",                 
      "code":400}}      
```

**How to reproduce**  

A simple test to reproduce is to try to index an empty array field:
```php
// get an update query instance
$update = $client->createUpdate();
$doc1 = $update->createDocument();
$doc1->id = 123;
$doc1->name = 'testdoc';
$doc1->price = 364;
$doc1->setField('collection_txt', [
                    0 => 'line 1',
                    1 => 'line 2',
                    2 => 'line 3',
]);
$doc1->setField('tags_txt_en', []);
$update->addDocument($doc1);
$update->addCommit();
$result = $client->update($update);
```

---

Here a dump of an update Query containing 2 documents to add to Solr, these 2 docs contain `id` field.
```
Solarium\QueryType\Update\Query\Query^ {#13746
  #options: array:4 [
    "handler" => "update"
    "resultclass" => "Solarium\QueryType\Update\Result"
    "documentclass" => "Solarium\QueryType\Update\Query\Document"
    "omitheader" => false
  ]
  #helper: null
  #params: []
  -localParameters: null
  #commandTypes: array:6 [
    "add" => "Solarium\QueryType\Update\Query\Command\Add"
    "commit" => "Solarium\QueryType\Update\Query\Command\Commit"
    "delete" => "Solarium\QueryType\Update\Query\Command\Delete"
    "optimize" => "Solarium\QueryType\Update\Query\Command\Optimize"
    "rawxml" => "Solarium\QueryType\Update\Query\Command\RawXml"
    "rollback" => "Solarium\QueryType\Update\Query\Command\Rollback"
  ]
  #commands: array:1 [
    0 => Solarium\QueryType\Update\Query\Command\Add^ {#449
      #options: []
      #documents: array:2 [
        0 => Solarium\QueryType\Update\Query\Document^ {#473
          #fields: array:19 [
            "id" => "62d911ce3144d1.02715591"
            "document_type_s" => "DocumentTranslation"
            "document_translation_id_i" => 1
            "document_id_i" => 1
            "created_at_dt" => "2021-09-17T10:19:59Z"
            "updated_at_dt" => "2022-06-23T14:00:35Z"
            "copyright_valid_since_dt" => "2022-06-15T19:00:00Z"
            "copyright_valid_until_dt" => "9999-12-31T22:59:59Z"
            "filename_s" => "2v3wckaloli_photo_1631298338669_7921e0c25422_crop_entropy_cs_srgb_fm_jpg_ixid_mnwyndmyodj8mhwxfhjhbmrvbxx8fhx8fhx8fde2mze4nzm5otk_ixlib_rb_1.2.1_q_85.jpg"
            "mime_type_s" => "image/jpeg"
            "locale_s" => "en"
            "title" => ""
            "title_txt_en" => ""
            "description_txt_en" => "city skyline during night time"
            "copyright_txt_en" => "Jeanson Wong, Unsplash"
            "tags_txt" => []
            "tags_txt_en" => ""
            "collection_txt" => array:3 [
              0 => ""
              1 => "city skyline during night time"
              2 => "Jeanson Wong, Unsplash"
            ]
            "collection_txt_en" => """
              \n
              city skyline during night time\n
              Jeanson Wong, Unsplash
              """
          ]
          #boost: null
          #modifiers: []
          #key: "id"
          #fieldBoosts: []
          #version: null
        }
        1 => Solarium\QueryType\Update\Query\Document^ {#457
          #fields: array:19 [
            "id" => "62d911ce3801f8.35434180"
            "document_type_s" => "DocumentTranslation"
            "document_translation_id_i" => 2
            "document_id_i" => 1
            "created_at_dt" => "2021-09-17T10:19:59Z"
            "updated_at_dt" => "2022-06-23T14:00:35Z"
            "copyright_valid_since_dt" => "2022-06-15T19:00:00Z"
            "copyright_valid_until_dt" => "9999-12-31T22:59:59Z"
            "filename_s" => "2v3wckaloli_photo_1631298338669_7921e0c25422_crop_entropy_cs_srgb_fm_jpg_ixid_mnwyndmyodj8mhwxfhjhbmrvbxx8fhx8fhx8fde2mze4nzm5otk_ixlib_rb_1.2.1_q_85.jpg"
            "mime_type_s" => "image/jpeg"
            "locale_s" => "fr"
            "title" => ""
            "title_txt_fr" => ""
            "description_txt_fr" => "city skyline during night time"
            "copyright_txt_fr" => "Jeanson Wong, Unsplash"
            "tags_txt" => []
            "tags_txt_fr" => ""
            "collection_txt" => array:3 [
              0 => ""
              1 => "city skyline during night time"
              2 => "Jeanson Wong, Unsplash"
            ]
            "collection_txt_fr" => """
              \n
              city skyline during night time\n
              Jeanson Wong, Unsplash
              """
          ]
          #boost: null
          #modifiers: []
          #key: "id"
          #fieldBoosts: []
          #version: null
        }
      ]
    }
  ]
}
```

Solr returns error at Query update: missing required field id

```
  Solr HTTP error: OK (400)                                          
  {                                                                  
    "responseHeader":{                                               
      "status":400,                                                  
      "QTime":1},                                                    
    "error":{                                                        
      "metadata":[                                                   
        "error-class","org.apache.solr.common.SolrException",        
        "root-error-class","org.apache.solr.common.SolrException"],  
      "msg":"[doc=null] missing required field: id",                 
      "code":400}} 
```

**Possible Solution**  
Fallback to v6.2.4 fixes this problem

### PR DESCRIPTION
**Pull request by thomascorthals**
Fixes #1023.

@mkalkbrenner Can we release 6.2.6 ASAP if this passes review? It's something I overlooked when fixing a nested child bug that's already causing issues for our users. :-(

Should we also delete release 6.2.5?

### CODE REVIEW

File: tests/QueryType/Update/RequestBuilderTest.php [hunk 1]
```diff
@@ -134,6 +134,23 @@ public function testBuildAddXmlMultivalueField()
...
+        $command = new AddCommand();
+        $command->addDocument(new Document(['id' => [1, 2, 3], 'text' => []]));
+
+        $this->assertSame(
+            '<add>'.
+            '<doc>'.
+            '<field name="id">1</field>'.
+            '<field name="id">2</field>'.
+            '<field name="id">3</field>'.
+            '</doc>'.
```
Comment (mkalkbrenner) [inline tests/QueryType/Update/RequestBuilderTest.php:148]: What will be the result of ```'text' => ['']```?

It is a valid pattern to index "empty" fields because it influences the scoring. There's a factor calculated from all documents that contain a field, regardless if it is empty.

I think we must provide a way to index this:
```
<doc>
            <field name="id">1</field>
            <field name="id">2</field>
            <field name="id">3</field>
            <field name="text"></field>
</doc>

Comment (thomascorthals) [reply tests/QueryType/Update/RequestBuilderTest.php:148]: It already worked. Added a unit test specifically for empty strings.

File: tests/QueryType/Update/RequestBuilderTest.php [hunk 2]
```diff
@@ -146,6 +146,39 @@ public function testBuildAddXmlMultivalueField()
...
+            '</add>',
+            $this->builder->buildAddXml($command)
+        );
+    }
+
+    public function testBuildAddXmlWithEmptyStrings()
```
Comment (mkalkbrenner) [inline tests/QueryType/Update/RequestBuilderTest.php:166]: As we had no test so far for that case I added one to the master to get that tested quickly:
https://github.com/solariumphp/solarium/commit/854794fdd2fd9b610f50029009ae05cc2a530f86

Now we have a redundant test ;-)

Comment (thomascorthals) [reply tests/QueryType/Update/RequestBuilderTest.php:166]: This bug proves that you can never have too many tests. ;-)

Comment (thomascorthals) [reply tests/QueryType/Update/RequestBuilderTest.php:166]: I changed the `id` to `0` to test for true emptiness. :-D
